spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: front
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
server:
  servlet:
    context-path: /front
  port: 8081